module.exports = [
  {
    id: 1,
    project: 'project1',
    status: 'open',
    dueDate: new Date(),
    updateDate: new Date(),
    summary: 'summary1',
    subject: 'hi this is a sentence',
    priority: 2,
    type: 'bug',
    created: new Date(),
    description: 'something is wrong',
    assignee: { id: 1, name: 'Dean Ma' },
    assigner: { id: 1, name: 'Dean Ma' },
    attachments: [],
  },
  {
    id: 3,
    project: 'project1',
    status: 'open',
    dueDate: new Date(),
    updateDate: new Date(),
    summary: 'summary1',
    subject: 'hi this is a sentence',
    priority: 2,
    type: 'bug',
    created: new Date(),
    description: 'something is wrong',
    assignee: { id: 1, name: 'Dean Ma' },
    assigner: { id: 1, name: 'Dean Ma' },
    attachments: [1],
  },
];