module.exports = [
  {
    id: 1,
    project: 'project1',
    status: 'open',
    dueDate: '2020/03/01',
    summary: 'summary1',
    subject: 'hi this is a sentence',
    priority: 1,
    type: 'bug',
    created: '2020/02/20',
    description: 'something is wrong',
    assignee: { id: 1, name: 'Dean Ma' },
    assigner: { id: 1, name: 'Dean Ma' },
    attachments: [],
  },
  {
    id: 2,
    project: 'project2',
    status: 'in_progress',
    dueDate: '2020/03/01',
    summary: 'summary1',
    subject: 'hi this is a sentence',
    priority: 2,
    type: 'bug',
    created: '2020/02/20',
    description: 'something is wrong',
    assignee: { id: 1, name: 'Dean Ma' },
    assigner: { id: 1, name: 'Dean Ma' },
    attachments: [],
  },
  {
    id: 3,
    project: 'project1',
    status: 'resolved',
    dueDate: '2020/03/01',
    summary: 'summary1',
    subject: 'hi this is a sentence',
    priority: 3,
    type: 'bug',
    created: '2020/02/20',
    description: 'something is wrong',
    assignee: { id: 1, name: 'Dean Ma' },
    assigner: { id: 1, name: 'Dean Ma' },
    attachments: [],
  },
];